// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTzjJwKlmSyRKuVIP5GsDZ_qihciX8nlk',
    appId: '1:1035954846797:web:532413ffbaa719d45ab004',
    messagingSenderId: '1035954846797',
    projectId: 'smart-home-project-73eb8',
    authDomain: 'smart-home-project-73eb8.firebaseapp.com',
    databaseURL: 'https://smart-home-project-73eb8-default-rtdb.firebaseio.com',
    storageBucket: 'smart-home-project-73eb8.appspot.com',
    measurementId: 'G-2G16JDEXJ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhFoxJ51lbksy6tDssf7uXfYnYH3CLrAU',
    appId: '1:1035954846797:android:914c0052742c26975ab004',
    messagingSenderId: '1035954846797',
    projectId: 'smart-home-project-73eb8',
    databaseURL: 'https://smart-home-project-73eb8-default-rtdb.firebaseio.com',
    storageBucket: 'smart-home-project-73eb8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCliFx76UD-SrWUMN40Ld5YM9rAawIcc9k',
    appId: '1:1035954846797:ios:639802f09264bf295ab004',
    messagingSenderId: '1035954846797',
    projectId: 'smart-home-project-73eb8',
    databaseURL: 'https://smart-home-project-73eb8-default-rtdb.firebaseio.com',
    storageBucket: 'smart-home-project-73eb8.appspot.com',
    iosBundleId: 'com.example.smartHome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCliFx76UD-SrWUMN40Ld5YM9rAawIcc9k',
    appId: '1:1035954846797:ios:639802f09264bf295ab004',
    messagingSenderId: '1035954846797',
    projectId: 'smart-home-project-73eb8',
    databaseURL: 'https://smart-home-project-73eb8-default-rtdb.firebaseio.com',
    storageBucket: 'smart-home-project-73eb8.appspot.com',
    iosBundleId: 'com.example.smartHome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTzjJwKlmSyRKuVIP5GsDZ_qihciX8nlk',
    appId: '1:1035954846797:web:64e3fc22025b2bdf5ab004',
    messagingSenderId: '1035954846797',
    projectId: 'smart-home-project-73eb8',
    authDomain: 'smart-home-project-73eb8.firebaseapp.com',
    databaseURL: 'https://smart-home-project-73eb8-default-rtdb.firebaseio.com',
    storageBucket: 'smart-home-project-73eb8.appspot.com',
    measurementId: 'G-Q69YVZD2EW',
  );
}
